FROM node:10.16-alpine

RUN apk --update upgrade && \
    apk add autoconf automake && \
    apk add libtool \
    git \
    g++ \
    libc6-compat \
    libjpeg-turbo-dev \
    libpng-dev \
    make \
    nasm
