App\Entity\User:
    attributes:
        email:
            groups: ['read_user', 'write_user']
        roles:
            groups: ['read_user', 'write_user']
        userProfile:
            groups: ['read_user']