resources:
    App\Entity\User:
        attributes:
            normalization_context:
                groups: ['read']
            denormalization_context:
                groups: ['write']
        collectionOperations:
            get:
                access_control: 'is_granted("ROLE_ADMIN")'
        itemOperations:
            get:
              access_control: 'is_granted("ROLE_ADMIN") or (is_granted("ROLE_USER") and object == user)'

    App\DTO\Role:
        properties:
            name:
                identifier: true
                attributes:
                    swagger_context:
                        type: string
        attributes:
            access_control: 'is_granted("ROLE_ADMIN")'
        collectionOperations:
            get: ~
        itemOperations:
            get: ~
